
package org.apache.account;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-05-15T14:09:53.907+02:00
 * Generated source version: 3.3.2
 *
 */
public final class AccountServiceImpl_AccountPort_Client {

    private static final QName SERVICE_NAME = new QName("http://apache.org/account", "AccountService");

    private AccountServiceImpl_AccountPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AccountService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AccountService ss = new AccountService(wsdlURL, SERVICE_NAME);
        AccountServiceImpl port = ss.getAccountPort();

        {
        System.out.println("Invoking findAccount...");
        org.apache.account.AccountRequest _findAccount_accountRequest = null;
        try {
            org.apache.account.AccountRespone _findAccount__return = port.findAccount(_findAccount_accountRequest);
            System.out.println("findAccount.result=" + _findAccount__return);

        } catch (AccountException_Exception e) {
            System.out.println("Expected exception: AccountException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking ping...");
        java.lang.String _ping_ping = "";
        port.ping(_ping_ping);


        }

        System.exit(0);
    }

}
